// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA_OReeBWh8pQclLcaWtN4q62TYQz08bk',
    appId: '1:1022176903157:web:6d49749c33699ac52b6abc',
    messagingSenderId: '1022176903157',
    projectId: 'stockapp-c62f7',
    authDomain: 'stockapp-c62f7.firebaseapp.com',
    storageBucket: 'stockapp-c62f7.firebasestorage.app',
    measurementId: 'G-4QEQB75D5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFyEFPDbBlIxpMRv-BKkA4qWTlQmTe1so',
    appId: '1:1022176903157:android:3c098728c6bf8ad52b6abc',
    messagingSenderId: '1022176903157',
    projectId: 'stockapp-c62f7',
    storageBucket: 'stockapp-c62f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu9qJ4yswjoY_fVIcE-4L6U2LaN7StpfE',
    appId: '1:1022176903157:ios:e59976e4137720402b6abc',
    messagingSenderId: '1022176903157',
    projectId: 'stockapp-c62f7',
    storageBucket: 'stockapp-c62f7.firebasestorage.app',
    iosBundleId: 'com.example.stockAppVer4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu9qJ4yswjoY_fVIcE-4L6U2LaN7StpfE',
    appId: '1:1022176903157:ios:e59976e4137720402b6abc',
    messagingSenderId: '1022176903157',
    projectId: 'stockapp-c62f7',
    storageBucket: 'stockapp-c62f7.firebasestorage.app',
    iosBundleId: 'com.example.stockAppVer4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCA_OReeBWh8pQclLcaWtN4q62TYQz08bk',
    appId: '1:1022176903157:web:b165e590836799382b6abc',
    messagingSenderId: '1022176903157',
    projectId: 'stockapp-c62f7',
    authDomain: 'stockapp-c62f7.firebaseapp.com',
    storageBucket: 'stockapp-c62f7.firebasestorage.app',
    measurementId: 'G-XYZ7YX15VY',
  );
}
